quarkus:
  banner:
    path: banner.txt
  mongodb:
    connection-string: mongodb://localhost:27017
    database: monitoramento-bancario
  datasource:
    db-kind: mysql
    username: root
    password: root
    jdbc:
      url: jdbc:mysql://localhost:3306/transacoes-falsas

mp:
  messaging:
    outgoing:
      transacao-banco:
        connector: smallrye-kafka
        topic: banco
        value:
          serializer: io.quarkus.kafka.client.serialization.JsonbSerializer
      transacao-cartao:
        connector: smallrye-kafka
        topic: cartao
        value:
          serializer: io.quarkus.kafka.client.serialization.JsonbSerializer
      transacao-financiamento:
        connector: smallrye-kafka
        topic: financiamento
        value:
          serializer: io.quarkus.kafka.client.serialization.JsonbSerializer
    incoming:
      banco:
        connector: smallrye-kafka
        value:
          deserializer: io.fraudes.scheduler.TransacaoDeserializer
      cartao:
        connector: smallrye-kafka
        value:
          deserializer: io.fraudes.scheduler.TransacaoDeserializer
      financiamento:
        connector: smallrye-kafka
        value:
          deserializer: io.fraudes.scheduler.TransacaoDeserializer
